[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "remotecook"
version = "0.1.0"
packages = ["remotecook"]
dependencies = ["flask>=3.0.0"]
